//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleMappingApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Common;
    
    public partial class ExampleMappingEntities : DbContext
    {
        public ExampleMappingEntities()
            : base("name=ExampleMappingEntities")
        {
        }
    
        public ExampleMappingEntities(ObjectContext objContext)
            : base(objContext, true)
        {
    
        }
        
        public ExampleMappingEntities(DbConnection connection)
            : base(connection, true)
        {
    
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EXAMPLE> EXAMPLE { get; set; }
    }
}
